// Code generated by cmd/workergen; DO NOT EDIT.
//go:build tinygo

package content

var embeddedSite = SiteConfig{Title: "diary", AuthorName: "James Yusuke", Description: "james-yusukeの個人的なブログです。", Bio: "個人的なことを載せてます。日記のようなものです。", GitHubURL: "https://github.com/james-yusuke", RepositoryURL: "https://github.com/james-yusuke", BaseURL: "http://localhost:8080"}

var embeddedPosts = []Post{}
