title: diary
author_name: James Yusuke
description: james-yusukeの個人的なブログです。
bio: 個人的なことを載せてます。日記のようなものです。
github_url: https://github.com/james-yusuke
repository_url: https://github.com/james-yusuke
base_url: http://localhost:8080
