// Command workergen compiles repository-managed content into TinyGo-safe Go
// source files. The Worker has no filesystem at runtime, so this command must
// run before tinygo build.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/james-yusuke/diary-blog/internal/content"
)

func main() {
	root := flag.String("root", ".", "project root")
	flag.Parse()
	configPath := filepath.Join(*root, "config", "site.yaml")
	postsDir := filepath.Join(*root, "content", "posts")
	store, err := content.Load(configPath, postsDir)
	if err != nil {
		fail(err)
	}
	if err := writeContent(filepath.Join(*root, "internal", "content", "embedded_tinygo_gen.go"), store); err != nil {
		fail(err)
	}
	css, err := os.ReadFile(filepath.Join(*root, "assets", "site.css"))
	if err != nil {
		fail(err)
	}
	if err := writeCSS(filepath.Join(*root, "internal", "site", "assets_tinygo_gen.go"), string(css)); err != nil {
		fail(err)
	}
}

func writeContent(path string, store *content.Store) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/workergen; DO NOT EDIT.\n//go:build tinygo\n\npackage content\n\nimport \"time\"\n\n")
	fmt.Fprintf(&b, "var embeddedSite = SiteConfig{Title: %q, AuthorName: %q, Description: %q, Bio: %q, GitHubURL: %q, RepositoryURL: %q, BaseURL: %q}\n\n", store.Site.Title, store.Site.AuthorName, store.Site.Description, store.Site.Bio, store.Site.GitHubURL, store.Site.RepositoryURL, store.Site.BaseURL)
	b.WriteString("var embeddedPosts = []Post{\n")
	for _, post := range store.Posts {
		fmt.Fprintf(&b, "{Slug: %q, Title: %q, Summary: %q, Published: time.Date(%d, time.Month(%d), %d, 0, 0, 0, 0, time.UTC), Tags: []string{%s}, Body: %q, HTML: %q, ReadingMins: %d},\n", post.Slug, post.Title, post.Summary, post.Published.Year(), post.Published.Month(), post.Published.Day(), quotedStrings(post.Tags), post.Body, post.HTML, post.ReadingMins)
	}
	b.WriteString("}\n")
	return writeFormatted(path, b.Bytes())
}

func writeCSS(path, css string) error {
	contents := "// Code generated by cmd/workergen; DO NOT EDIT.\n//go:build tinygo\n\npackage site\n\nconst workerCSS = " + fmt.Sprintf("%q", css) + "\n"
	return writeFormatted(path, []byte(contents))
}

func quotedStrings(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}

func writeFormatted(path string, source []byte) error {
	formatted, err := format.Source(source)
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

func fail(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
